cd go
mkdir logs
cd logs
touch golang.log
cd ../../
cd rust
mkdir logs
cd logs
touch logs_api_gateway.log
touch logs_auth_service.log
touch logs_faculty_service.log
touch logs_lecture_service.log
touch logs_schedule_service.log
touch logs_staff_service.log