version: '3.9'
services:
  mongo-db:
    image: mongo
    container_name: mongo-golang
    restart: always
    environment:
      MONGO_INITDB_DATABASE: user_db
    ports:
      - "27018:27017"

  golang:
    image: romana98/golang:latest
    container_name: golang
    depends_on:
      - mongo-db
    volumes:
      - type: bind
        source: ./logs/golang.log
        target: /golang/logs/logs.log
    environment:
      MONGODB_URI: mongodb://mongo-db
      LOG_STORAGE: /golang/logs/logs.log
    ports:
      - '8080:8080'
      
  frontend-app:
    image: romana98/frontend-app:latest
    container_name: frontend-go
    ports:
      - '4200:4200'
