version: '3.9' # optional since v1.27.0
services:
  frontend-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend-app
    container_name: frontend-app
    ports:
      - '4200:4200'
