use crate::endpoints::*;
use actix_web::web;

pub fn config_services(cfg: &mut web::ServiceConfig) {
    cfg.service (
        web::scope("/") 
            .service(check::healthcheck)
            .service(
                web::scope("/auth")
                    .service(
                        web::resource("/log-in")
                            .route(web::post().to(auth_api::login))
                    )
            )
            .service(
                web::scope("/staff")
                    .service(
                        web::resource("")
                            .route(web::post().to(staff_api::create_staff))
                            .route(web::put().to(staff_api::update_staff))
                            .route(web::get().to(staff_api::get_all_staff))
                    )   
                    .service(
                        web::resource("/{id}")
                            .route(web::get().to(staff_api::get_staff))
                            .route(web::delete().to(staff_api::delete_staff))
                    )
            )
            .service(
                web::scope("/soft-constraints")
                    .service(
                        web::resource("")
                            .route(web::put().to(soft_constraints_api::update_soft_constraints))
                            .route(web::get().to(soft_constraints_api::get_soft_constraints))
                    )
            )
            .service(
                web::scope("/lectures")
                    .service(
                        web::resource("")
                            .route(web::post().to(lecture_api::create_lecture))
                            .route(web::put().to(lecture_api::update_lecture))
                            .route(web::get().to(lecture_api::get_all_lectures))
                    )
                    .service(
                        web::resource("/by-faculty")
                            .route(web::post().to(lecture_api::get_all_lectures_by_ids))
                    )
                    .service(
                        web::resource("/by-staff")
                            .route(web::get().to(staff_api::get_all_lectures_by_staff))
                    )
                    .service(
                        web::resource("/{id}")
                            .route(web::get().to(lecture_api::get_lecture))
                            .route(web::delete().to(lecture_api::delete_lecture))
                    )   
            )
            .service(
                web::scope("/shifts")
                    .service(
                        web::resource("")
                            .route(web::post().to(shift_api::create_shift))
                            .route(web::put().to(shift_api::update_shift))
                            .route(web::get().to(shift_api::get_all_shifts))
                    )
                    .service(
                        web::resource("/{id}")
                            .route(web::get().to(shift_api::get_shift))
                            .route(web::delete().to(shift_api::delete_shift))
                    )
            )
            .service(
                web::scope("/hard-constraints")
                .service(
                    web::resource("")
                        .route(web::post().to(hard_constraints_api::create_hard_constraint))
                        .route(web::put().to(hard_constraints_api::update_hard_constraint))
                        .route(web::get().to(hard_constraints_api::get_all_hard_constraints))
                )
                .service(
                    web::resource("/{id}")
                        .route(web::get().to(hard_constraints_api::get_hard_constraint))
                        .route(web::delete().to(hard_constraints_api::delete_hard_constraint))
                )
            )
            .service(
                web::scope("/faculties")
                .service(
                    web::resource("")
                        .route(web::post().to(faculty_api::create_faculty))
                        .route(web::put().to(faculty_api::update_faculty))
                        .route(web::get().to(faculty_api::get_all_faculties))
                )
                .service(
                    web::resource("/{id}")
                        .route(web::get().to(faculty_api::get_faculty))
                        .route(web::delete().to(faculty_api::delete_faculty))
                )
            )
            .service(
                web::scope("/schedule")
                .service(
                    web::resource("")
                        .route(web::post().to(schedule_api::generate_schedule))
                )
                .service(
                    web::resource("/{id}")
                        //.route(web::get().to(faculty_api::get_faculty)))
                )
                .service(
                    web::resource("/by-staff")
                        //.route(web::get().to(faculty_api::get_faculty)))
                )
            )
    );
}